---
title: "R Deep Neural Network"
output: html_notebook
---

#Intal Packages
```{r}
install.packages("keras")
install.packages("mlbench")
install.packages("magrittr")
```


```{r}
library(keras)
library(mlbench)
library(dplyr)
library(magrittr)
library(neuralnet)
```

#Data
```{r}
data("BostonHousing")
data <- BostonHousing
str(data)
```

```{r}
data %<>% mutate_if(is.factor, as.numeric)
str(data)
```

#Neural Network Visualization
```{r}
n <- neuralnet(medv~ crim+zn+indus+chas+nox+rm+age+dis+rad+tax+ptratio+b+lstat,
               data = data, 
               hidden = c(10,5),
               linear.output = F,
               lifesign = "full",
               rep = 1)
```

```{r}
plot(n,
     col.hidden = "darkgreen",
     col.hidden.synapse = "darkgreen",
     show.weight = F,
     information = F,
     fill = "lightblue")
```


#Matrix
```{r}
data <- as.matrix(data)
dimnames(data) <- NULL
```


#Partition 
```{r}
set.seed(1234)
indDN <- sample(2, nrow(data), replace = T, prob = c(.7,.3))
trainingDN <- data[indDN==1,1:13]
testDN <- data[indDN==2, 1:13]
trainingtarget <- data[indDN==1,14]
testtarget <- data[indDN==2,14]
```

#Normalize
```{r}
m <- colMeans(trainingDN)
s <- apply(trainingDN, 2, sd)
trainingDN <- scale(trainingDN, center = m, scale = s)
testDN <- scale(testDN, center = m, scale = s)
```

#Create a Model
```{r}
model <- keras_model_sequential()
model %>% 
        layer_dense(units = 5, activation = "relu", input_shape =c(13)) %>% 
        layer_dense(units = 1)
```

