---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(ggplot2)
library(gganimate)
```

svmPer

```{r}
svmPer <- read.csv("svmpPerfomance_df.csv")
svmPer
```


```{r}
p <- ggplot(svmPer, aes(dispersion, error, size = epsilon, colour = cost)) +
  geom_point(alpha = 0.7, show.legend = FALSE)+
  labs(title = "Error dispersion for SVM best model: {frame_time}", x = "Dispersion", y = "Error") + 
    transition_time(dispersion) +
    ease_aes('linear')
p
```

```{r}
anim_save('svmPlot.gif', animate(p))
   list(src = 'svmplot.gif',
        contentType = 'image/gif',
        width =600,
        height =500,
        alt = "Error Dispersion for SVM best Model NSP dependant")
```

```{r}
+
      transition_time(dispersion) +
      ease_aes('linear')
    
   anim_save('svmPlot.gif', animate(p))
   list(src = 'svmplot.gif',
        contentType = 'image/gif',
        width =600,
        height =500,
        alt = "Error Dispersion for SVM best Model NSP dependant")
```



```{r}
theTree 
```

 
```{r}
p <- theTree %>% 
  ggplot(mapping = aes('left daughter','right daughter', color = 'split var')) + geom_point()
p
```
 

